#!/bin/sh

# Set ownership and permissions
chown dsf:dsf /opt/dsf/plugins/MaintenanceTimers.json
chmod 440 /opt/dsf/plugins/MaintenanceTimers.json

chown -R dsf:dsf /opt/dsf/plugins/MaintenanceTimers
chmod 550 /opt/dsf/plugins/MaintenanceTimers/dsf/MaintenanceTimersPlugin

chown dsf:dsf /opt/dsf/sd/sys/timers.json
chmod 660 /opt/dsf/sd/sys/timers.json

# Restart DCS to load the new manifest and then restart the plugin
if (systemctl is-active -q duetcontrolserver); then
	systemctl restart duetcontrolserver
	if (systemctl is-active -q duetpluginservice); then
		/opt/dsf/bin/PluginManager start MaintenanceTimers
	fi
fi

# Don't block the configuration of other packages if DPS failed to start
exit 0
