#!/bin/sh

# Set ownership and permissions
chown dsf:dsf /opt/dsf/plugins/MaintenanceTimers.json
chmod 440 /opt/dsf/plugins/MaintenanceTimers.json

chown -R dsf:dsf /opt/dsf/plugins/MaintenanceTimers
chmod 550 /opt/dsf/plugins/MaintenanceTimers/dsf/MaintenanceTimersPlugin

chown dsf:dsf /opt/dsf/sd/sys/timers.json
chmod 660 /opt/dsf/sd/sys/timers.json

# Reload the plugin manifest
if [ -f /opt/dsf/plugins/MaintenanceTimers/.start ]; then
        rm /opt/dsf/plugins/MaintenanceTimers/.start
        if (systemctl is-active -q duetcontrolserver && systemctl is-active -q duetpluginservice && systemctl is-active -q duetpluginservice-root); then
                /opt/dsf/bin/PluginManager -q reload MaintenanceTimers
                /opt/dsf/bin/PluginManager -q start MaintenanceTimers
        else
                echo "MaintenanceTimers" >> /opt/dsf/conf/plugins.txt
        fi
fi

# Don't block the configuration of other packages if DPS failed to start
exit 0
